version: 2
jobs:
  build: # runs not using Workflows must have a `build` job as entry point
    working_directory: ~/arle # directory where steps will run
    docker: # run the steps with Docker
      - image: circleci/node:11.7 # ...with this image as the primary container; this is where all `steps` will run
    #   - image: mongo:3.4.4 # and this image as the secondary service container
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory
      - run:
          name: Use latest NPM
          command: 'sudo npm install -g npm@latest'
      - restore_cache: # special step to restore the dependency cache
          key: npm-install-{{ checksum "package-lock.json" }}
      - run:
          name: Run npm install
          command: npm install
      - save_cache: # special step to save the dependency cache
          key: npm-install-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run linter
          command: npm run test:lint
      - run:
          name: Run tests
          command: npm run test:ci
          environment:
            JEST_JUNIT_OUTPUT: ./test-results/jest/results.xml
      #   - store_artifacts: # special step to save test results as as artifact
      #       path: test-results.xml
      #       prefix: tests
      #
      - run:
          name: Upload Coverage
          command: sudo npm install -g codecov && codecov
      - store_test_results: # special step to upload test results for display in Test Summary
          path: test-results
          prefix: tests
      - store_artifacts:
          path: coverage
          prefix: coverage
